// This file is auto-generated by `scraper/emit_ts_vocab.py` from
// `scraper/ai_vocab.json`. DO NOT EDIT by hand — rerun the emit script.
// See ADR-012 for the single-source-of-truth pipeline.

/* eslint-disable */

// AI tag union — Claude's enrich.py may return only these keys.
export type AITag =
  | 'paved_access'
  | 'seasonal_access_only'
  | 'remote_access_concerns'
  | 'utilities_on_site'
  | 'off_grid_viable'
  | 'infrastructure_needed'
  | 'water_rights_present'
  | 'year_round_water'
  | 'seasonal_water_only'
  | 'no_water_mentioned'
  | 'build_ready'
  | 'buildable_with_work'
  | 'difficult_terrain'
  | 'soil_suitable_for_ag'
  | 'remote_living_viable'
  | 'near_services'
  | 'isolated'
  | 'agricultural_potential'
  | 'timber_harvestable'
  | 'hunting_viable'
  | 'grazing_suitable'
  | 'no_hoa'
  | 'hoa_present'
  | 'deed_restrictions'
  | 'zoning_concerns'
  | 'flood_risk_mentioned'
  | 'fire_risk_mentioned'
  | 'mineral_rights_excluded';

export const AI_TAG_KEYS: readonly AITag[] = [
  'paved_access',
  'seasonal_access_only',
  'remote_access_concerns',
  'utilities_on_site',
  'off_grid_viable',
  'infrastructure_needed',
  'water_rights_present',
  'year_round_water',
  'seasonal_water_only',
  'no_water_mentioned',
  'build_ready',
  'buildable_with_work',
  'difficult_terrain',
  'soil_suitable_for_ag',
  'remote_living_viable',
  'near_services',
  'isolated',
  'agricultural_potential',
  'timber_harvestable',
  'hunting_viable',
  'grazing_suitable',
  'no_hoa',
  'hoa_present',
  'deed_restrictions',
  'zoning_concerns',
  'flood_risk_mentioned',
  'fire_risk_mentioned',
  'mineral_rights_excluded',
] as const;

export const AI_TAG_LABELS: Record<AI_TAG, string> = {
  paved_access: "Paved Access",
  seasonal_access_only: "Seasonal Access",
  remote_access_concerns: "Remote Access",
  utilities_on_site: "Utilities On-Site",
  off_grid_viable: "Off-Grid Viable",
  infrastructure_needed: "Infrastructure Needed",
  water_rights_present: "Water Rights",
  year_round_water: "Year-Round Water",
  seasonal_water_only: "Seasonal Water",
  no_water_mentioned: "No Water Mentioned",
  build_ready: "Build-Ready",
  buildable_with_work: "Buildable w/ Work",
  difficult_terrain: "Difficult Terrain",
  soil_suitable_for_ag: "Good Ag Soil",
  remote_living_viable: "Remote Living",
  near_services: "Near Services",
  isolated: "Isolated",
  agricultural_potential: "Agriculture",
  timber_harvestable: "Timber",
  hunting_viable: "Hunting",
  grazing_suitable: "Grazing",
  no_hoa: "No HOA",
  hoa_present: "HOA Present",
  deed_restrictions: "Deed Restrictions",
  zoning_concerns: "Zoning Issues",
  flood_risk_mentioned: "Flood Risk",
  fire_risk_mentioned: "Fire Risk",
  mineral_rights_excluded: "Mineral Rights Excluded",
};

// Red flag union — Claude's enrich.py may return only these keys.
export type RedFlag =
  | 'hoa_restrictions'
  | 'flood_zone_mention'
  | 'wetland_restrictions'
  | 'no_water_source'
  | 'no_road_access'
  | 'easement_concerns'
  | 'environmental_hazard'
  | 'title_issues_mentioned'
  | 'tax_sale_risk'
  | 'requires_septic_install'
  | 'requires_well_drilling'
  | 'zoning_prohibits_residential'
  | 'extreme_remote'
  | 'price_seems_too_good';

export const RED_FLAG_KEYS: readonly RedFlag[] = [
  'hoa_restrictions',
  'flood_zone_mention',
  'wetland_restrictions',
  'no_water_source',
  'no_road_access',
  'easement_concerns',
  'environmental_hazard',
  'title_issues_mentioned',
  'tax_sale_risk',
  'requires_septic_install',
  'requires_well_drilling',
  'zoning_prohibits_residential',
  'extreme_remote',
  'price_seems_too_good',
] as const;

export const RED_FLAG_LABELS: Record<RED_FLAG, string> = {
  hoa_restrictions: "HOA Restrictions",
  flood_zone_mention: "Flood Zone",
  wetland_restrictions: "Wetland",
  no_water_source: "No Water Source",
  no_road_access: "No Road Access",
  easement_concerns: "Easement Concerns",
  environmental_hazard: "Environmental Hazard",
  title_issues_mentioned: "Title Issues",
  tax_sale_risk: "Tax Sale Risk",
  requires_septic_install: "Needs Septic",
  requires_well_drilling: "Needs Well",
  zoning_prohibits_residential: "Zoning: No Residential",
  extreme_remote: "Extremely Remote",
  price_seems_too_good: "Price Too Good",
};

// Severity 1-5 (higher = worse). Used by UI to prioritize flag display.
export const RED_FLAG_SEVERITY: Record<RedFlag, number> = {
  hoa_restrictions: 2,
  flood_zone_mention: 4,
  wetland_restrictions: 3,
  no_water_source: 5,
  no_road_access: 5,
  easement_concerns: 3,
  environmental_hazard: 5,
  title_issues_mentioned: 5,
  tax_sale_risk: 4,
  requires_septic_install: 2,
  requires_well_drilling: 2,
  zoning_prohibits_residential: 5,
  extreme_remote: 2,
  price_seems_too_good: 4,
};
