"""Emit TypeScript types + label maps for the AI vocabulary.

Reads `scraper/ai_vocab.json` and writes
`frontend/src/types/ai-vocab.generated.ts`. This is the single-source-of-truth
pipeline described in ADR-012.

Usage:
    python -m scraper.emit_ts_vocab            # write (idempotent)
    python -m scraper.emit_ts_vocab --check    # exit 1 if output would differ

CI runs --check so PRs that touch the JSON without regenerating the .ts are
caught before merge.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
VOCAB_JSON = Path(__file__).parent / "ai_vocab.json"
OUTPUT_TS = REPO_ROOT / "frontend" / "src" / "types" / "ai-vocab.generated.ts"


HEADER = """// This file is auto-generated by `scraper/emit_ts_vocab.py` from
// `scraper/ai_vocab.json`. DO NOT EDIT by hand — rerun the emit script.
// See ADR-012 for the single-source-of-truth pipeline.
"""


def render_ts(vocab: dict) -> str:
    tag_entries = vocab["aiTags"]
    flag_entries = vocab["redFlags"]

    def union(entries: list[dict]) -> str:
        return "\n  | ".join(f"'{e['key']}'" for e in entries)

    def labels(entries: list[dict], const_name: str, key_type: str) -> str:
        lines = [
            f"  {e['key']}: {json.dumps(e['label'])},"  # json.dumps handles quoting
            for e in entries
        ]
        body = "\n".join(lines)
        return (
            f"export const {const_name}: Record<{key_type}, string> = {{\n{body}\n}};"
        )

    out: list[str] = [HEADER.rstrip(), ""]
    out.append("// AI tag union — Claude's enrich.py may return only these keys.")
    out.append(f"export type AITag =\n  | {union(tag_entries)};")
    out.append("")
    out.append("export const AI_TAG_KEYS: readonly AITag[] = [")
    for e in tag_entries:
        out.append(f"  '{e['key']}',")
    out.append("] as const;")
    out.append("")
    out.append(labels(tag_entries, "AI_TAG_LABELS", "AITag"))
    out.append("")
    out.append("// Red flag union — Claude's enrich.py may return only these keys.")
    out.append(f"export type RedFlag =\n  | {union(flag_entries)};")
    out.append("")
    out.append("export const RED_FLAG_KEYS: readonly RedFlag[] = [")
    for e in flag_entries:
        out.append(f"  '{e['key']}',")
    out.append("] as const;")
    out.append("")
    out.append(labels(flag_entries, "RED_FLAG_LABELS", "RedFlag"))
    out.append("")
    out.append(
        "// Severity 1-5 (higher = worse). Used by UI to prioritize flag display."
    )
    out.append("export const RED_FLAG_SEVERITY: Record<RedFlag, number> = {")
    for e in flag_entries:
        out.append(f"  {e['key']}: {int(e['severity'])},")
    out.append("};")
    out.append("")
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the generated file would differ from the existing one.",
    )
    args = parser.parse_args()

    with VOCAB_JSON.open() as fh:
        vocab = json.load(fh)

    rendered = render_ts(vocab)
    current = OUTPUT_TS.read_text() if OUTPUT_TS.exists() else ""

    if args.check:
        if rendered != current:
            print(
                f"error: {OUTPUT_TS.relative_to(REPO_ROOT)} is out of date. "
                f"Run `python -m scraper.emit_ts_vocab` and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"ok: {OUTPUT_TS.relative_to(REPO_ROOT)} matches ai_vocab.json")
        return 0

    OUTPUT_TS.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_TS.write_text(rendered)
    print(f"wrote {OUTPUT_TS.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
