"""Stage 4 (optional): generate a starter scraper module from a probed
candidate. Fills in the 80% boilerplate — imports, class skeleton,
fetch/parse stubs picked based on the detected render_type. The
human finishes the parse() logic by hand.

Usage:
    python -m discovery.scaffold <domain> [--render next.js_ssr]

Writes `scraper/sources/{slug}.py` and prints follow-up TODOs.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Iterable

_THIS_DIR = Path(__file__).resolve().parent
_SOURCES_DIR = _THIS_DIR.parent / "sources"


_NEXT_JS_TEMPLATE = '''"""{title} scraper — https://www.{domain}

Auto-generated by discovery.scaffold on {date}. The site was detected
as Next.js SSR — the whole page's listing set ships as JSON inside
`<script id="__NEXT_DATA__">`, so parsing is a JSON pull, not HTML.

TODO for the reviewer:
  * Inspect `props.pageProps` keys on a live page to find the listing
    array name (varies site-to-site — LandHub uses `dataFromServer`).
  * Fill in _STATE_SLUGS with the URL slug the site uses (often the
    state name lowercase, occasionally the 2-letter code).
  * Map the row fields onto RawListing in parse().
  * Wire into config.ENABLED_SOURCES and main.py ALL_SCRAPERS.
"""

from __future__ import annotations

import json
import re
from typing import Any

from logger import get_logger

from .base import BaseScraper, RawListing
from .landwatch import extract_features

log = get_logger("scraper.{slug}")

_NEXT_DATA_RE = re.compile(
    r'<script id="__NEXT_DATA__" type="application/json">(.*?)</script>',
    re.DOTALL,
)

# TODO: populate with the URL slugs this site uses per state.
_STATE_SLUGS = {{
    "MO": "missouri",
    "AR": "arkansas",
}}


def _extract(html: str) -> list[dict[str, Any]]:
    m = _NEXT_DATA_RE.search(html)
    if not m:
        return []
    try:
        data = json.loads(m.group(1))
    except (json.JSONDecodeError, ValueError):
        return []
    # TODO: replace `dataFromServer` with the right key for this site.
    rows = data.get("props", {{}}).get("pageProps", {{}}).get("dataFromServer")
    if not isinstance(rows, list):
        return []
    return [r for r in rows if isinstance(r, dict)]


class {class_name}(BaseScraper):
    SOURCE_NAME = "{slug}"
    BASE_URL = "https://www.{domain}"
    RATE_LIMIT_SECONDS = 2.5

    def _page_url(self, state: str, page: int) -> str:
        slug = _STATE_SLUGS.get(state.upper())
        if not slug:
            return ""
        # TODO: adjust path to match the site's search URL shape.
        return f"{{self.BASE_URL}}/land-for-sale/{{slug}}/?page={{page}}"

    def fetch(self, state: str, max_pages: int = 5) -> list[dict[str, Any]]:
        rows: list[dict[str, Any]] = []
        seen: set[Any] = set()
        for page in range(1, max(1, max_pages) + 1):
            url = self._page_url(state, page)
            if not url:
                return []
            try:
                result = self.fetch_page(url)
            except Exception as e:
                log.info(f"[{slug}] {{state}} page {{page}} fetch failed: {{e}}")
                break
            page_rows = _extract(result.content)
            if not page_rows:
                break
            fresh = 0
            for r in page_rows:
                rid = r.get("id")
                if rid is None or rid in seen:
                    continue
                seen.add(rid)
                rows.append(r)
                fresh += 1
            if fresh == 0:
                break
        log.info(f"[{slug}] {{state}}: {{len(rows)}} listings")
        return rows

    def parse(self, raw: dict[str, Any]) -> RawListing | None:
        # TODO: map each raw JSON row to RawListing fields. The fields
        # below are common — adjust to match this site's schema.
        try:
            listing_id = raw.get("id")
            title = str(raw.get("title") or "").strip()
            price = float(raw.get("price") or 0)
            acres = float(raw.get("acres") or 0)
            if not title or price <= 0 or acres <= 0:
                return None
            return RawListing(
                external_id=str(listing_id),
                title=title,
                price=price,
                acreage=acres,
                state="",  # TODO
                county=str(raw.get("county") or ""),
                lat=None,  # TODO
                lng=None,  # TODO
                features=extract_features(title),
                description=title,
                url=f"{{self.BASE_URL}}/property/{{listing_id}}",
                images=[],  # TODO
                raw=raw,
            )
        except Exception as e:
            log.info(f"[{slug}] parse error: {{e}}")
            return None
'''


_SERVER_RENDERED_TEMPLATE = '''"""{title} scraper — https://www.{domain}

Auto-generated by discovery.scaffold on {date}. Detected as
server-rendered HTML with identifiable listing cards.

TODO for the reviewer:
  * Inspect a live page to find the card CSS selector.
  * Map card sub-elements onto RawListing fields in parse().
  * Fill in lat/lng extraction if present on data-attributes.
  * Wire into config.ENABLED_SOURCES and main.py ALL_SCRAPERS.
"""

from __future__ import annotations

import re
from typing import Any

from bs4 import BeautifulSoup

from logger import get_logger

from .base import BaseScraper, RawListing
from .landwatch import extract_features

log = get_logger("scraper.{slug}")

_PRICE_RE = re.compile(r"\\$([\\d,]+)")
_ACRES_RE = re.compile(r"([\\d.,]+)\\s*(?:\\pm|\\+/-|\\+-)?\\s*[Aa]cres?")

# TODO: populate with per-state URL slugs.
_STATE_SLUGS = {{
    "MO": "missouri",
    "AR": "arkansas",
}}


def _parse_html(html: str, state: str) -> list[dict[str, Any]]:
    soup = BeautifulSoup(html, "lxml")
    # TODO: replace this selector with the actual card class on {domain}.
    cards = soup.select("div.listing-card, div.property-card")
    results: list[dict[str, Any]] = []
    for card in cards:
        text = card.get_text(" ", strip=True)
        m_price = _PRICE_RE.search(text)
        m_acres = _ACRES_RE.search(text)
        price = float(m_price.group(1).replace(",", "")) if m_price else 0.0
        acres = float(m_acres.group(1).replace(",", "")) if m_acres else 0.0
        # TODO: pull title, link, id, images, lat/lng from card attrs.
        results.append(
            {{
                "id": card.get("data-id", ""),
                "title": text[:80],
                "url": "",
                "price": price,
                "acres": acres,
                "state": state,
            }}
        )
    return results


class {class_name}(BaseScraper):
    SOURCE_NAME = "{slug}"
    BASE_URL = "https://www.{domain}"
    RATE_LIMIT_SECONDS = 2.5

    def fetch(self, state: str, max_pages: int = 5) -> list[dict[str, Any]]:
        slug = _STATE_SLUGS.get(state.upper())
        if not slug:
            return []
        url = f"{{self.BASE_URL}}/land-for-sale/{{slug}}/"
        try:
            result = self.fetch_page(url)
        except Exception as e:
            log.info(f"[{slug}] fetch failed: {{e}}")
            return []
        return _parse_html(result.content, state)

    def parse(self, raw: dict[str, Any]) -> RawListing | None:
        # TODO: map raw → RawListing.
        title = str(raw.get("title") or "").strip()
        if not title:
            return None
        return RawListing(
            external_id=str(raw.get("id", "")) or str(hash(title))[:10],
            title=title,
            price=float(raw.get("price") or 0),
            acreage=float(raw.get("acres") or 0),
            state=str(raw.get("state", "")).upper(),
            county="",
            url=str(raw.get("url", "")),
            features=extract_features(title),
            description=title,
            images=[],
            raw=raw,
        )
'''


def _slugify(domain: str) -> str:
    """myfarm-broker.com → myfarm_broker. Uses the leftmost non-`www`
    label so multi-part TLDs (.co.uk, .com.au) don't leak into the
    slug. Assumes input is host-form already, no scheme."""
    host = domain.lower().split(":")[0]
    if host.startswith("www."):
        host = host[4:]
    # Leftmost label is the brand in 99% of cases now that `www.` is
    # gone. Subdomains (api.brand.com) are a trade-off — the api vs
    # brand distinction isn't meaningful for naming the scraper.
    base = host.split(".", 1)[0]
    slug = re.sub(r"[^a-z0-9]+", "_", base).strip("_")
    return slug or "newsource"


def _class_name(slug: str) -> str:
    """rural_farms → RuralFarmsScraper"""
    parts = [p for p in slug.split("_") if p]
    return "".join(p.capitalize() for p in parts) + "Scraper"


_TEMPLATES = {
    "next.js_ssr": _NEXT_JS_TEMPLATE,
    "server_rendered_cards": _SERVER_RENDERED_TEMPLATE,
}


def write_source(
    domain: str,
    render_type: str,
    *,
    overwrite: bool = False,
    out_dir: Path | None = None,
) -> Path:
    """Render the appropriate template and write to sources/{slug}.py."""
    from datetime import date

    slug = _slugify(domain)
    target_dir = out_dir or _SOURCES_DIR
    target = target_dir / f"{slug}.py"
    if target.exists() and not overwrite:
        raise FileExistsError(f"{target} already exists; pass overwrite=True")
    template = _TEMPLATES.get(render_type, _SERVER_RENDERED_TEMPLATE)
    body = template.format(
        title=domain.replace(".", " ").title(),
        domain=domain,
        slug=slug,
        class_name=_class_name(slug),
        date=date.today().isoformat(),
    )
    target.write_text(body)
    return target


def _cli(argv: Iterable[str]) -> int:
    ap = argparse.ArgumentParser(prog="discovery.scaffold")
    ap.add_argument("domain", help="Candidate domain (e.g. myfarms.com)")
    ap.add_argument(
        "--render",
        default="server_rendered_cards",
        choices=sorted(_TEMPLATES.keys()),
    )
    ap.add_argument("--overwrite", action="store_true")
    args = ap.parse_args(list(argv))

    path = write_source(args.domain, args.render, overwrite=args.overwrite)
    print(f"Scaffolded {path}")
    print()
    print("Next steps:")
    print(f"  1. Edit {path} — search for 'TODO' to see what to fill in.")
    print(f"  2. Register in scraper/main.py ALL_SCRAPERS.")
    print(f"  3. Enable in scraper/config.py ENABLED_SOURCES.")
    print(f"  4. Run: python main.py --dry-run --source={_slugify(args.domain)}")
    return 0


if __name__ == "__main__":
    sys.exit(_cli(sys.argv[1:]))
